// ---- Small-count presets (2–4 children) ----

function presetLayout(items, gap) {
  const n = items.length;

  if (n === 2) {
    const [a, b] = items;
    const maxH = Math.max(a.h, b.h);
    return [
      { id: a.id, x: 0,         y: Math.round((maxH - a.h) / 2) },
      { id: b.id, x: a.w + gap, y: Math.round((maxH - b.h) / 2) },
    ];
  }

  if (n === 3) {
    const [a, b, c] = items;
    const rowW    = a.w + gap + b.w;
    const rowMaxH = Math.max(a.h, b.h);
    const bottomY = c.h + gap;
    const topX    = Math.max(0, Math.round(rowW / 2 - c.w / 2));
    return [
      { id: a.id, x: 0,         y: bottomY + Math.round((rowMaxH - a.h) / 2) },
      { id: b.id, x: a.w + gap, y: bottomY + Math.round((rowMaxH - b.h) / 2) },
      { id: c.id, x: topX,      y: 0 },
    ];
  }

  if (n === 4) {
    const [a, b, c, d] = items;
    const col0W = Math.max(a.w, c.w);
    const row0H = Math.max(a.h, b.h);
    return [
      { id: a.id, x: 0,           y: 0 },
      { id: b.id, x: col0W + gap, y: 0 },
      { id: c.id, x: 0,           y: row0H + gap },
      { id: d.id, x: col0W + gap, y: row0H + gap },
    ];
  }

  return null;
}

// ---- Annular bin-pack (5+ children) ----
//
// Candidates are generated by orbiting around placed items at bounding-circle
// distance.  Collision is checked with actual rect intersection so no circle
// over-approximation wastes space.  Every accepted position is then slid
// toward the origin until it would cause a rect overlap, giving tight packing.
//
// items:   [{ id, w, h }]
// returns: [{ id, x, y }]  — top-left corners, min shifted to (0, 0)

function annularPack(items, gap) {
  const sorted = [...items]
    .map(item => ({ ...item, r: Math.hypot(item.w, item.h) / 2 }))
    .sort((a, b) => b.r - a.r);

  // placed items store center coords
  const placed = [];

  function rectOverlap(ax, ay, aw, ah, bx, by, bw, bh) {
    return ax < bx + bw + gap &&
           ax + aw + gap > bx &&
           ay < by + bh + gap &&
           ay + ah + gap > by;
  }

  // cx, cy = candidate center
  function overlaps(cx, cy, cw, ch) {
    const tlx = cx - cw / 2, tly = cy - ch / 2;
    return placed.some(p => rectOverlap(tlx, tly, cw, ch, p.x - p.w / 2, p.y - p.h / 2, p.w, p.h));
  }

  // Slide a candidate center toward origin as far as possible without overlap
  function tighten(cx, cy, cw, ch) {
    const dist = Math.hypot(cx, cy);
    if (dist < 1) return { x: cx, y: cy };
    const ux = -cx / dist, uy = -cy / dist;
    const STEP = 2;
    let x = cx, y = cy;
    for (let i = 0, lim = Math.ceil(dist / STEP) + 1; i < lim; i++) {
      const nx = x + ux * STEP, ny = y + uy * STEP;
      if (overlaps(nx, ny, cw, ch)) break;
      x = nx; y = ny;
      if (Math.hypot(x, y) < STEP) { x = 0; y = 0; break; }
    }
    return { x, y };
  }

  for (const c of sorted) {
    if (!placed.length) {
      placed.push({ ...c, x: 0, y: 0 });
      continue;
    }

    let bestX = 0, bestY = 0, bestDist = Infinity;

    for (const p of placed) {
      // Orbit at bounding-circle distance — guarantees we sample valid arcs
      const orbitR = p.r + c.r + gap;
      const steps  = Math.max(32, Math.round((2 * Math.PI * orbitR) / (Math.min(c.w, c.h) * 0.3)));
      for (let k = 0; k < steps; k++) {
        const angle = (k / steps) * 2 * Math.PI;
        const px = p.x + orbitR * Math.cos(angle);
        const py = p.y + orbitR * Math.sin(angle);
        if (overlaps(px, py, c.w, c.h)) continue;
        const { x: tx, y: ty } = tighten(px, py, c.w, c.h);
        const d = tx * tx + ty * ty;
        if (d < bestDist) { bestDist = d; bestX = tx; bestY = ty; }
      }
    }

    placed.push({ ...c, x: bestX, y: bestY });
  }

  const minX = Math.min(...placed.map(p => p.x - p.w / 2));
  const minY = Math.min(...placed.map(p => p.y - p.h / 2));

  return placed.map(p => ({
    id: p.id,
    x: Math.round(p.x - p.w / 2 - minX),
    y: Math.round(p.y - p.h / 2 - minY),
  }));
}

// ---- Public entry point ----

export function annularBinPack(items, opts = {}) {
  if (!items.length) return [];
  const { gap = 16 } = opts;
  return presetLayout(items, gap) ?? annularPack(items, gap);
}
// ---- Small-count presets (2–4 children) ----

function presetLayout(items, gap) {
  const n = items.length;

  if (n === 2) {
    const [a, b] = items;
    const maxH = Math.max(a.h, b.h);
    return [
      { id: a.id, x: 0,         y: Math.round((maxH - a.h) / 2) },
      { id: b.id, x: a.w + gap, y: Math.round((maxH - b.h) / 2) },
    ];
  }

  if (n === 3) {
    const [a, b, c] = items;
    const rowW    = a.w + gap + b.w;
    const rowMaxH = Math.max(a.h, b.h);
    const bottomY = c.h + gap;
    const topX    = Math.max(0, Math.round(rowW / 2 - c.w / 2));
    return [
      { id: a.id, x: 0,         y: bottomY + Math.round((rowMaxH - a.h) / 2) },
      { id: b.id, x: a.w + gap, y: bottomY + Math.round((rowMaxH - b.h) / 2) },
      { id: c.id, x: topX,      y: 0 },
    ];
  }

  if (n === 4) {
    const [a, b, c, d] = items;
    const col0W = Math.max(a.w, c.w);
    const row0H = Math.max(a.h, b.h);
    return [
      { id: a.id, x: 0,           y: 0 },
      { id: b.id, x: col0W + gap, y: 0 },
      { id: c.id, x: 0,           y: row0H + gap },
      { id: d.id, x: col0W + gap, y: row0H + gap },
    ];
  }

  return null;
}

// ---- Annular bin-pack (5+ children) ----
//
// Candidates are generated by orbiting around placed items at bounding-circle
// distance.  Collision is checked with actual rect intersection so no circle
// over-approximation wastes space.  Every accepted position is then slid
// toward the origin until it would cause a rect overlap, giving tight packing.
//
// items:   [{ id, w, h }]
// returns: [{ id, x, y }]  — top-left corners, min shifted to (0, 0)

function annularPack(items, gap) {
  const sorted = [...items]
    .map(item => ({ ...item, r: Math.hypot(item.w, item.h) / 2 }))
    .sort((a, b) => b.r - a.r);

  // placed items store center coords
  const placed = [];

  function rectOverlap(ax, ay, aw, ah, bx, by, bw, bh) {
    return ax < bx + bw + gap &&
           ax + aw + gap > bx &&
           ay < by + bh + gap &&
           ay + ah + gap > by;
  }

  // cx, cy = candidate center
  function overlaps(cx, cy, cw, ch) {
    const tlx = cx - cw / 2, tly = cy - ch / 2;
    return placed.some(p => rectOverlap(tlx, tly, cw, ch, p.x - p.w / 2, p.y - p.h / 2, p.w, p.h));
  }

  // Slide a candidate center toward origin as far as possible without overlap
  function tighten(cx, cy, cw, ch) {
    const dist = Math.hypot(cx, cy);
    if (dist < 1) return { x: cx, y: cy };
    const ux = -cx / dist, uy = -cy / dist;
    const STEP = 2;
    let x = cx, y = cy;
    for (let i = 0, lim = Math.ceil(dist / STEP) + 1; i < lim; i++) {
      const nx = x + ux * STEP, ny = y + uy * STEP;
      if (overlaps(nx, ny, cw, ch)) break;
      x = nx; y = ny;
      if (Math.hypot(x, y) < STEP) { x = 0; y = 0; break; }
    }
    return { x, y };
  }

  for (const c of sorted) {
    if (!placed.length) {
      placed.push({ ...c, x: 0, y: 0 });
      continue;
    }

    let bestX = 0, bestY = 0, bestDist = Infinity;

    for (const p of placed) {
      // Orbit at bounding-circle distance — guarantees we sample valid arcs
      const orbitR = p.r + c.r + gap;
      const steps  = Math.max(32, Math.round((2 * Math.PI * orbitR) / (Math.min(c.w, c.h) * 0.3)));
      for (let k = 0; k < steps; k++) {
        const angle = (k / steps) * 2 * Math.PI;
        const px = p.x + orbitR * Math.cos(angle);
        const py = p.y + orbitR * Math.sin(angle);
        if (overlaps(px, py, c.w, c.h)) continue;
        const { x: tx, y: ty } = tighten(px, py, c.w, c.h);
        const d = tx * tx + ty * ty;
        if (d < bestDist) { bestDist = d; bestX = tx; bestY = ty; }
      }
    }

    placed.push({ ...c, x: bestX, y: bestY });
  }

  const minX = Math.min(...placed.map(p => p.x - p.w / 2));
  const minY = Math.min(...placed.map(p => p.y - p.h / 2));

  return placed.map(p => ({
    id: p.id,
    x: Math.round(p.x - p.w / 2 - minX),
    y: Math.round(p.y - p.h / 2 - minY),
  }));
}

// ---- Public entry point ----

export function annularBinPack(items, opts = {}) {
  if (!items.length) return [];
  const { gap = 16 } = opts;
  return presetLayout(items, gap) ?? annularPack(items, gap);
}
